# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstBuildJob
    steps:
    - bash: echo First Jobs
    - bash: echo $(PipelineAuthor)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
  # - job: SecondBuildJob
  #   steps:
  #   - bash: echo Build Second Jobs
# - stage: DevDeploy
#   variables: 
#     environment: Development
#   dependsOn: Build
#   jobs:
#   - job: DevFirstJob
#     steps:
#     - bash: echo $(environment) First Jop
# - stage: QADeploy
#   variables: 
#     environment: QA
#   dependsOn: Build
#   jobs:
#   - job: QAFirstJob
#     steps:
#     - bash: echo echo $(environment) First Jobs
# - stage: ProductionDeploy
#   variables: 
#     environment: Production
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdFirstJob
#     steps:
#     - bash: echo echo $(environment) First Jobs
